import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

type ArtifactProject = {
  slug: string;
  name: string;
  description: string;
  details: Record<string, unknown>;
  artifacts: Array<{ key: string; title: string; content: string }>;
};

type WireframeSpec = {
  appKind: 'invoice_factoring' | 'generic_workflow';
  title: string;
  mission: string;
  audience: string;
  runtime: string;
  backend: string;
  themeMode: string;
  fontFamily: string;
  logoHref: string;
  primary: string;
  accent: string;
  success: string;
  navItems: string[];
  entities: string[];
  workflow: Array<{ title: string; detail: string }>;
  checklist: string[];
  statusRows: string[][];
  kpis: Array<{ label: string; value: string }>;
  heroTitle: string;
  primaryAction: string;
  secondaryAction: string;
  statusTitle: string;
  checklistTitle: string;
  tableTitle: string;
  tableHeaders: string[];
  tableNote: string;
  mobileTitle: string;
  mobileBadge: string;
  mobileCardTitle: string;
  mobileCardText: string;
  mobilePreviewLabel: string;
  mobileFields: string[];
  mobileAction: string;
  stackNote: string;
  integrationNote: string;
};

const ARTIFACT_ROOT = '/opt';
const REQUIRED_ARTIFACTS = ['proposal', 'specs', 'design', 'tasks', 'verification', 'archive'];

export function writeProjectArtifacts(project: ArtifactProject) {
  const projectDir = join(ARTIFACT_ROOT, project.slug);
  resetGeneratedArtifacts(projectDir);
  const capability = safeSegment(text(project.details.capabilityName, project.slug), project.slug);
  const changeId = safeSegment(text(project.details.changeId, `add-${project.slug}`), `add-${project.slug}`);
  const specDir = join(projectDir, 'openspec', 'specs', capability);
  const changeDir = join(projectDir, 'openspec', 'changes', changeId);
  const changeSpecDir = join(changeDir, 'specs', capability);

  mkdirSync(specDir, { recursive: true });
  mkdirSync(changeSpecDir, { recursive: true });
  mkdirSync(join(projectDir, '.vscode'), { recursive: true });
  mkdirSync(join(projectDir, 'docs'), { recursive: true });

  const artifacts = new Map(project.artifacts.map((artifact) => [artifact.key, artifact.content]));
  for (const key of REQUIRED_ARTIFACTS) {
    if (!artifacts.get(key)?.trim()) {
      throw new Error(`Cannot write project artifacts: missing generated ${key} content`);
    }
  }
  writeFileSync(join(projectDir, 'README.md'), renderReadme(project, changeId), 'utf8');
  writeFileSync(join(projectDir, 'AGENTS.md'), renderAgentInstructions(project), 'utf8');
  writeFileSync(join(projectDir, '.vscode', 'settings.json'), renderVSCodeSettings(), 'utf8');
  writeFileSync(join(projectDir, '.vscode', 'extensions.json'), renderVSCodeExtensions(), 'utf8');
  writeFileSync(join(projectDir, 'openspec', 'config.yaml'), renderOpenSpecConfig(project), 'utf8');
  writeFileSync(join(projectDir, 'openspec', 'project.md'), renderProjectConventions(project), 'utf8');
  writeFileSync(join(specDir, 'spec.md'), artifacts.get('specs') ?? '', 'utf8');
  writeFileSync(join(changeDir, 'proposal.md'), artifacts.get('proposal') ?? '', 'utf8');
  writeFileSync(join(changeDir, 'design.md'), artifacts.get('design') ?? '', 'utf8');
  writeFileSync(join(changeDir, 'tasks.md'), artifacts.get('tasks') ?? '', 'utf8');
  writeFileSync(join(changeSpecDir, 'spec.md'), artifacts.get('specs') ?? '', 'utf8');
  writeFileSync(join(projectDir, 'docs', 'ai-sanity-check.md'), renderSanityCheckProtocol(project), 'utf8');
  writeFileSync(join(projectDir, 'docs', 'builder-inputs.md'), renderBuilderInputs(project), 'utf8');
  writeFileSync(join(projectDir, 'docs', 'verification.md'), artifacts.get('verification') ?? '', 'utf8');
  writeFileSync(join(projectDir, 'docs', 'archive.md'), artifacts.get('archive') ?? '', 'utf8');
  writeFileSync(join(projectDir, 'project.json'), JSON.stringify(project, null, 2), 'utf8');
  const logoHref = writeLogo(project, join(projectDir, 'public', 'brand'));
  writeWireframe(project, join(projectDir, 'docs', 'wireframe'), logoHref);
}

export function deleteProjectArtifacts(slug: string) {
  rmSync(join(ARTIFACT_ROOT, slug), { recursive: true, force: true });
}

function resetGeneratedArtifacts(projectDir: string) {
  rmSync(join(projectDir, 'openspec'), { recursive: true, force: true });
  rmSync(join(projectDir, 'docs', 'wireframe'), { recursive: true, force: true });
  rmSync(join(projectDir, 'public', 'brand'), { recursive: true, force: true });
}

function renderReadme(project: ArtifactProject, changeId: string) {
  const capability = safeSegment(text(project.details.capabilityName, project.slug), project.slug);
  return `# ${project.name}

${project.description || 'Generated by OpenSpec-Builder.'}

## VS Code Chat Handoff

Open this folder directly in VS Code:

\`\`\`bash
code /opt/${project.slug}
\`\`\`

Then ask your chat agent to read \`AGENTS.md\`, \`openspec/project.md\`, and the active change under \`openspec/changes/${changeId}\` before writing code.

## Project Layout

- \`AGENTS.md\`
- \`.vscode/\`
- \`openspec/config.yaml\`
- \`openspec/project.md\`
- \`openspec/specs/${capability}/spec.md\`
- \`openspec/changes/${changeId}/proposal.md\`
- \`openspec/changes/${changeId}/design.md\`
- \`openspec/changes/${changeId}/tasks.md\`
- \`openspec/changes/${changeId}/specs/${capability}/spec.md\`
- \`public/brand/\`
- \`docs/wireframe/\`
- \`docs/builder-inputs.md\`
- \`docs/verification.md\`
- \`docs/archive.md\`
- \`project.json\`
`;
}

function renderAgentInstructions(project: ArtifactProject) {
  const changeId = safeSegment(text(project.details.changeId, `add-${project.slug}`), `add-${project.slug}`);
  return `# Agent Instructions

You are building ${project.name}. Treat this folder as the application repository root.

## Selected Coding Environment

- Target chat extension: ${text(project.details.targetChatExtension, 'TBD')}
- Agent/model packs: ${list(project.details.agentModels)}
- Desired skills/MCPs: ${list(project.details.skills)}
- Technology stack: ${text(project.details.technologyStack, 'TBD')}
- Runtime: ${text(project.details.runtimeOption, 'TBD')}
- Backend: ${text(project.details.backendFramework, 'TBD')}
- Additional tech stack requirements: ${text(project.details.additionalTechStackRequirements, 'None specified')}
- Styling: ${list(project.details.styling)}
- Theme mode: ${text(project.details.mode, 'TBD')}
- Palette: ${list(project.details.palette)}
- Fonts: ${text(project.details.primaryFont, 'TBD')} / ${text(project.details.secondaryFont, 'TBD')}
- Icon library: ${text(project.details.fontLibrary, 'TBD')}
- Docker: ${text(project.details.dockerStrategy, 'TBD')}
- Cloudflared: ${text(project.details.cloudflared, 'TBD')}
- Portainer: ${text(project.details.portainer, 'TBD')}

## Before Coding

1. Read \`openspec/project.md\`.
2. Read \`openspec/config.yaml\`.
3. Read \`docs/builder-inputs.md\`.
4. Read \`openspec/changes/${changeId}/proposal.md\`.
5. Read \`openspec/changes/${changeId}/design.md\`.
6. Read \`openspec/changes/${changeId}/tasks.md\`.
7. Read all specs under \`openspec/changes/${changeId}/specs/\`.

## Rules

- Do not implement outside the approved OpenSpec scope.
- Keep generated app assets in conventional project locations.
- Use \`public/brand/\` for logo and brand assets.
- Use \`docs/wireframe/\` as visual reference, not production source.
- Follow the stack, backend, additional stack requirements, Docker, styling, palette, fonts, icon library, and agent instructions in \`openspec/config.yaml\` and \`docs/builder-inputs.md\`.
- Run the AI Sanity Check Protocol below before coding and at each major build milestone.
- Validate the OpenSpec change before final handoff when tooling is available:
  \`${text(project.details.validationCommand, `openspec validate ${changeId} --strict`)}\`

${renderSanityCheckProtocol(project)}

## Superpowers

If available, install or enable Superpowers before implementation:

\`\`\`text
/plugin marketplace add obra/superpowers-marketplace
/plugin install superpowers@superpowers-marketplace
\`\`\`
`;
}

function renderOpenSpecConfig(project: ArtifactProject) {
  const details = project.details;
  const isFactoringProject = isInvoiceFactoringProject(project);
  const domainText = (value: unknown, fallback: string) => normalizeDomainText(text(value, fallback), isFactoringProject);
  return `schema: spec-driven

context: |${yamlBlock([
    `Product: ${project.name}`,
    `Mission: ${project.description ? normalizeDomainText(project.description, isFactoringProject) : domainText(details.mission, 'TBD')}`,
    `Audience: ${domainText(details.audience, 'TBD')}`,
    `Audience sophistication: ${domainText(details.audienceSophistication, 'TBD')}`,
    `Tech stack: ${text(details.technologyStack, 'TBD')}`,
    `Runtime: ${text(details.runtimeOption, 'TBD')}`,
    `Backend: ${text(details.backendFramework, 'TBD')}`,
    `Additional tech stack requirements: ${domainText(details.additionalTechStackRequirements, 'None specified')}`,
    `Stack interpretation: ${stackInterpretation(details)}`,
    `Styling: ${list(details.styling)}`,
    `Theme mode: ${text(details.mode, 'TBD')}`,
    `Mood style: ${text(details.moodStyle, 'TBD')}`,
    `Palette option: ${text(details.selectedPaletteOption, 'TBD')}`,
    `Palette colors: ${list(details.palette)}`,
    `Fonts: ${text(details.primaryFont, 'TBD')} primary, ${text(details.secondaryFont, 'TBD')} secondary`,
    `Icon library: ${text(details.fontLibrary, 'TBD')}`,
    `Docker: ${text(details.dockerStrategy, 'TBD')}`,
    `Cloudflared: ${text(details.cloudflared, 'TBD')}`,
    `Portainer: ${text(details.portainer, 'TBD')}`,
    `Target chat extension: ${text(details.targetChatExtension, 'TBD')}`,
    `Agent packs: ${list(details.agentModels)}`,
    `Desired skills/MCPs: ${list(details.skills)}`,
    `Main workflow: ${domainText(details.mainWorkflow, 'TBD')}`,
    `Data needs: ${domainText(details.dataNeeds, 'TBD')}`,
    `Integrations: ${domainText(details.integrations, 'None specified')}`,
    `Constraints: ${domainText(details.constraints, 'None specified')}`
  ])}

rules:
  proposal:
    - Include stack, backend, deployment, agent, and brand choices in implementation impact.
  design:
    - Treat selected stack, backend, additional stack requirements, styling, palette, fonts, icons, Docker, Cloudflared, and Portainer choices as implementation constraints.
    - Include data model and integration implications for the selected backend.
  specs:
    - Use SHALL/MUST for normative requirements.
    - Use Given/When/Then scenario format.
    - Include at least one scenario proving the app follows the approved stack and brand constraints.
  tasks:
    - Include setup tasks for dependencies, backend configuration, styling tokens, Docker/deployment, and verification.

sanity_check_protocol:
  cadence:
    - Before writing code.
    - After scaffolding the project foundation.
    - After backend, database, auth, storage, API, or deployment architecture changes.
    - After each major workflow or screen group.
    - After every 8-12 meaningfully edited files, or roughly every 60-90 minutes in a long coding session.
    - Before declaring any milestone complete.
    - Before final handoff.
    - Immediately when implementation conflicts with project intent, selected stack, security constraints, mobile layout, deployment choices, brand system, or wireframe direction.
  required_review:
    - Compare implementation against AGENTS.md, openspec/config.yaml, docs/builder-inputs.md, proposal.md, design.md, tasks.md, specs, and docs/wireframe.
    - Confirm stack, backend, Docker/deployment, styling, colors, fonts, icons, navigation, data model, integrations, and constraints still match the approved selections.
    - Report decisions made, mismatches found, risks, missing specs, tests run, and exact next actions.
`;
}

function renderVSCodeSettings() {
  return `${JSON.stringify(
    {
      'chat.agent.promptFiles': true,
      'files.exclude': {
        '**/node_modules': true,
        '**/.DS_Store': true
      }
    },
    null,
    2
  )}
`;
}

function renderVSCodeExtensions() {
  return `${JSON.stringify(
    {
      recommendations: [
        'esbenp.prettier-vscode',
        'bradlc.vscode-tailwindcss'
      ]
    },
    null,
    2
  )}
`;
}

function renderProjectConventions(project: ArtifactProject) {
  const changeId = safeSegment(text(project.details.changeId, `add-${project.slug}`), `add-${project.slug}`);
  const capability = safeSegment(text(project.details.capabilityName, project.slug), project.slug);
  return `# Project Conventions

## Product

${project.name}

## Mission

${project.description || text(project.details.mission, 'TBD')}

## OpenSpec Workflow

- Profile: ${text(project.details.openspecProfile, 'Default artifact-guided workflow')}
- Change ID: ${changeId}
- Capability: ${capability}
- Validate before implementation: \`${text(project.details.validationCommand, `openspec validate ${changeId} --strict`)}\`
- Always-on context: \`openspec/config.yaml\`
- Full Builder input ledger: \`docs/builder-inputs.md\`
- Do not implement before proposal approval.
- Use \`#### Scenario:\` headings for scenarios.
- Prefer SHALL/MUST for normative requirements.

## Stack and Runtime

- Technology stack: ${text(project.details.technologyStack, 'TBD')}
- Runtime: ${text(project.details.runtimeOption, 'TBD')}
- Backend: ${text(project.details.backendFramework, 'TBD')}
- Additional tech stack requirements: ${text(project.details.additionalTechStackRequirements, 'None specified')}
- Stack interpretation: ${stackInterpretation(project.details)}
- Docker: ${text(project.details.dockerStrategy, 'TBD')}
- Cloudflared: ${text(project.details.cloudflared, 'TBD')}
- Portainer: ${text(project.details.portainer, 'TBD')}

## Brand and UI

- Styling: ${list(project.details.styling)}
- Theme mode: ${text(project.details.mode, 'TBD')}
- Mood: ${text(project.details.moodStyle, 'TBD')}
- Palette option: ${text(project.details.selectedPaletteOption, 'TBD')}
- Palette colors: ${list(project.details.palette)}
- Fonts: ${text(project.details.primaryFont, 'TBD')} / ${text(project.details.secondaryFont, 'TBD')}
- Icons: ${text(project.details.fontLibrary, 'TBD')}
`;
}

function renderBuilderInputs(project: ArtifactProject) {
  const d = project.details;
  return `# Builder Inputs

This file records every OpenSpec-Builder wizard field in markdown so coding agents do not need to inspect \`project.json\` to understand Builder intent.

## Product Intent

- Project name: ${project.name}
- Mission/problem: ${project.description || text(d.mission, 'TBD')}
- Intended audience: ${text(d.audience, 'TBD')}
- Audience sophistication: ${text(d.audienceSophistication, 'TBD')}
- User actions: ${text(d.userActions, 'TBD')}
- Main workflow: ${text(d.mainWorkflow, 'TBD')}
- Data needs: ${text(d.dataNeeds, 'TBD')}
- Integrations/devices/APIs: ${text(d.integrations, 'None specified')}
- Out of scope: ${text(d.outOfScope, 'None specified')}
- Constraints/risks: ${text(d.constraints, 'None specified')}

## Technology Choices

- Technology stack: ${text(d.technologyStack, 'TBD')}
- Runtime option: ${text(d.runtimeOption, 'TBD')}
- Backend framework: ${text(d.backendFramework, 'TBD')}
- Additional tech stack requirements: ${text(d.additionalTechStackRequirements, 'None specified')}
- Docker containers: ${text(d.dockerStrategy, 'TBD')}
- Cloudflared: ${text(d.cloudflared, 'TBD')}
- Portainer: ${text(d.portainer, 'TBD')}

## AI Coding Agent Choices

- Target chat extension: ${text(d.targetChatExtension, 'TBD')}
- Agent/model packs: ${list(d.agentModels)}
- Desired skills/MCPs: ${list(d.skills)}
- OpenSpec profile: ${text(d.openspecProfile, 'Default artifact-guided workflow')}

## Styling and Brand Choices

- Styling libraries: ${list(d.styling)}
- Theme mode: ${text(d.mode, 'TBD')}
- Mood style: ${text(d.moodStyle, 'TBD')}
- Selected palette option: ${text(d.selectedPaletteOption, 'TBD')}
- Palette colors: ${list(d.palette)}
- Extracted logo colors: ${list(d.extractedLogoColors)}
- Primary font: ${text(d.primaryFont, 'TBD')}
- Secondary font: ${text(d.secondaryFont, 'TBD')}
- Icon library: ${text(d.fontLibrary, 'TBD')}
- Logo file: ${text(d.logoFileName, 'No logo uploaded')}
- Logo MIME type: ${text(d.logoMimeType, 'N/A')}

## OpenSpec Fields

- Capability name: ${text(d.capabilityName, project.slug)}
- Change ID: ${text(d.changeId, `add-${project.slug}`)}
- Delta operation: ${text(d.deltaOperation, 'ADDED')}
- Proposal why: ${text(d.proposalWhy, 'TBD')}
- Proposal changes: ${text(d.proposalChanges, 'TBD')}
- Proposal impact: ${text(d.proposalImpact, 'TBD')}
- Affected specs: ${text(d.affectedSpecs, text(d.capabilityName, project.slug))}
- Affected code: ${text(d.affectedCode, 'TBD')}
- Requirement name: ${text(d.requirementName, 'TBD')}
- Requirement statement: ${text(d.requirementStatement, 'TBD')}
- Scenario name: ${text(d.scenarioName, 'TBD')}
- Scenario GIVEN: ${text(d.scenarioGiven, 'TBD')}
- Scenario WHEN: ${text(d.scenarioWhen, 'TBD')}
- Scenario THEN: ${text(d.scenarioThen, 'TBD')}
- Task plan: ${text(d.taskPlan, 'TBD')}
- Design context: ${text(d.designContext, 'TBD')}
- Design goals: ${text(d.designGoals, 'TBD')}
- Design non-goals: ${text(d.designNonGoals, 'TBD')}
- Design decisions: ${text(d.designDecisions, 'TBD')}
- Risks/tradeoffs: ${text(d.risksTradeoffs, 'TBD')}
- Migration plan: ${text(d.migrationPlan, 'TBD')}
- Open questions: ${text(d.openQuestions, 'None')}
- Validation command: ${text(d.validationCommand, `openspec validate ${text(d.changeId, `add-${project.slug}`)} --strict`)}
`;
}

function renderSanityCheckProtocol(project: ArtifactProject) {
  const changeId = safeSegment(text(project.details.changeId, `add-${project.slug}`), `add-${project.slug}`);
  return `## AI Sanity Check Protocol

At the checkpoints below, stop and produce a short written sanity check before continuing. Do not bury this inside code comments.

### Required Inputs

- \`AGENTS.md\`
- \`openspec/config.yaml\`
- \`docs/builder-inputs.md\`
- \`docs/wireframe/index.html\`
- \`openspec/changes/${changeId}/proposal.md\`
- \`openspec/changes/${changeId}/design.md\`
- \`openspec/changes/${changeId}/tasks.md\`
- All specs under \`openspec/changes/${changeId}/specs/\`

### Cadence

- Before writing code.
- After scaffolding the app foundation.
- After backend, database, auth, storage, API, or deployment architecture changes.
- After each major workflow or screen group.
- After every 8-12 meaningfully edited files, or roughly every 60-90 minutes in a long coding session.
- Before declaring any milestone complete.
- Before final handoff.
- Immediately when implementation conflicts with Builder intent, stack, backend, security, mobile layout, Docker/deployment, brand system, or wireframe direction.

### Output Format

\`\`\`text
AI Sanity Check
- Builder intent still matched: yes/no
- Stack/backend/deployment still matched: yes/no
- UI/navigation/brand/wireframe still matched: yes/no
- Data/security/integration constraints still matched: yes/no
- Files reviewed:
- Tests or commands run:
- Mismatches or risks:
- Decision needed from Builder:
- Next implementation step:
\`\`\`

If any answer is "no", pause implementation unless the mismatch is clearly documented as a deliberate, low-risk tradeoff.
`;
}

function writeLogo(project: ArtifactProject, logoDir: string): string {
  const dataUrl = text(project.details.logoDataUrl, '');
  if (!dataUrl.startsWith('data:image/')) return '';
  const match = dataUrl.match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,(.+)$/);
  if (!match) return '';
  const mimeType = match[1] ?? 'image/png';
  const payload = match[2] ?? '';
  const extension = logoExtension(text(project.details.logoFileName, ''), mimeType);
  mkdirSync(logoDir, { recursive: true });
  const fileName = `logo.${extension}`;
  writeFileSync(join(logoDir, fileName), Buffer.from(payload, 'base64'));
  return `../../public/brand/${fileName}`;
}

function writeWireframe(project: ArtifactProject, wireframeDir: string, logoHref: string) {
  mkdirSync(wireframeDir, { recursive: true });
  writeFileSync(join(wireframeDir, 'index.html'), renderWireframe(project, logoHref), 'utf8');
}

function renderWireframe(project: ArtifactProject, logoHref: string) {
  const palette = Array.isArray(project.details.palette) ? project.details.palette.map(String) : [];
  const primary = normalizeHex(palette[0], '#22d3ee');
  const accent = normalizeHex(palette[1], '#8b5cf6');
  const success = normalizeHex(palette[2], '#10b981');
  const spec = deriveWireframeSpec(project);
  const isFactoringProject = isInvoiceFactoringProject(project);
  const audience = text(project.details.audience, 'Target audience to be refined');
  const runtime = text(project.details.runtimeOption, 'Runtime TBD');
  const backend = text(project.details.backendFramework, 'Backend TBD');
  const mission = normalizeDomainText(project.description || text(project.details.mission, 'Mission pending'), isFactoringProject);
  const logo = logoHref;
  const navItems = spec.navItems;
  const entities = spec.entities;
  const workflow = spec.workflow;
  const statusRows = spec.statusRows;
  const checklist = spec.checklist;

  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${escapeHtml(project.name)} Wireframe</title>
    <style>
      :root {
        color-scheme: dark;
        --bg: #07080a;
        --surface: #111317;
        --surface-2: #171a20;
        --line: #2b3038;
        --text: #f4f4f5;
        --muted: #a4abb6;
        --primary: ${primary};
        --accent: ${accent};
        --success: ${success};
        --warning: #f5b842;
        --danger: #ef4444;
      }
      * { box-sizing: border-box; }
      body { margin: 0; min-height: 100vh; background: radial-gradient(circle at top left, color-mix(in srgb, var(--primary) 18%, transparent), transparent 34%), var(--bg); color: var(--text); font-family: ${escapeCssIdentifier(text(project.details.primaryFont, 'Inter'))}, Inter, ui-sans-serif, system-ui, sans-serif; }
      .shell { display: grid; grid-template-columns: 292px minmax(0, 1fr); min-height: 100vh; }
      main { min-width: 0; padding: 24px; }
      aside { border-right: 1px solid var(--line); padding: 18px; background: rgba(14, 16, 20, .84); backdrop-filter: blur(18px); }
      .topbar { display: flex; justify-content: space-between; gap: 18px; align-items: center; margin-bottom: 20px; }
      .brand { display: flex; align-items: center; gap: 10px; min-width: 0; }
      .brand img { width: 42px; height: 42px; object-fit: contain; border-radius: 10px; background: #ffffff; }
      .brand strong { display: block; font-size: 18px; }
      .brand span, p, small { color: var(--muted); }
      h1 { margin: 0 0 8px; font-size: 32px; letter-spacing: 0; line-height: 1.05; max-width: 780px; }
      h2, h3 { margin: 0; letter-spacing: 0; }
      p { line-height: 1.55; }
      .actions { display: flex; flex-wrap: wrap; gap: 10px; }
      .button { display: inline-flex; align-items: center; justify-content: center; min-height: 38px; border: 1px solid var(--line); border-radius: 8px; padding: 9px 12px; color: var(--text); background: var(--surface-2); font-weight: 650; white-space: nowrap; }
      .button.primary { color: #050507; background: var(--text); border-color: var(--text); }
      .button.accent { color: #050507; background: var(--warning); border-color: var(--warning); }
      .hero { display: grid; grid-template-columns: minmax(0, 1.1fr) minmax(280px, .9fr); gap: 16px; align-items: stretch; margin-bottom: 16px; }
      .panel { border: 1px solid var(--line); border-radius: 14px; background: rgba(17, 19, 23, .92); padding: 18px; box-shadow: 0 16px 60px rgba(0,0,0,.24); }
      .hero-card { min-height: 238px; display: grid; align-content: space-between; }
      .kpis { display: grid; grid-template-columns: repeat(3, minmax(0, 1fr)); gap: 10px; margin-top: 18px; }
      .kpi { border: 1px solid var(--line); border-radius: 10px; padding: 12px; background: #0d0f13; }
      .kpi strong { display: block; font-size: 22px; margin-top: 6px; }
      .content { display: grid; grid-template-columns: minmax(0, 1.15fr) minmax(280px, .85fr); gap: 16px; align-items: start; }
      .section-head { display: flex; justify-content: space-between; gap: 12px; align-items: center; margin-bottom: 14px; }
      .checklist { display: grid; gap: 9px; }
      .check-item { display: grid; grid-template-columns: 26px minmax(0, 1fr) auto; gap: 10px; align-items: center; border: 1px solid var(--line); border-radius: 10px; padding: 10px; background: #0d0f13; }
      .check { width: 22px; height: 22px; border-radius: 7px; display: grid; place-items: center; color: #06110b; background: var(--success); font-size: 13px; font-weight: 900; }
      .check.empty { background: transparent; border: 1px solid var(--line); color: var(--muted); }
      .pill { border: 1px solid var(--line); border-radius: 999px; padding: 4px 8px; color: var(--muted); font-size: 12px; }
      .pill.good { color: #07130a; background: var(--success); border-color: var(--success); font-weight: 800; }
      .pill.warn { color: #181002; background: var(--warning); border-color: var(--warning); font-weight: 800; }
      table { width: 100%; border-collapse: collapse; overflow: hidden; }
      th, td { border-bottom: 1px solid var(--line); padding: 11px 8px; text-align: left; font-size: 14px; }
      th { color: var(--muted); font-weight: 650; }
      .timeline { display: grid; gap: 12px; margin-top: 14px; }
      .timeline-row { display: grid; grid-template-columns: 12px minmax(0,1fr); gap: 10px; align-items: start; }
      .dot { width: 12px; height: 12px; border-radius: 99px; margin-top: 5px; background: var(--primary); box-shadow: 0 0 0 4px color-mix(in srgb, var(--primary) 18%, transparent); }
      .phone { max-width: 330px; margin: 0 auto; border: 1px solid var(--line); border-radius: 28px; padding: 12px; background: #050608; box-shadow: inset 0 0 0 1px rgba(255,255,255,.04); }
      .phone-screen { min-height: 520px; border-radius: 20px; background: var(--surface); overflow: hidden; display: grid; grid-template-rows: auto 1fr auto; }
      .phone-head { padding: 16px; border-bottom: 1px solid var(--line); display: flex; justify-content: space-between; align-items: center; }
      .phone-body { padding: 14px; display: grid; gap: 12px; align-content: start; }
      .upload-card { border: 1px solid var(--line); border-radius: 13px; padding: 13px; background: #0d0f13; }
      .capture { height: 130px; border-radius: 12px; border: 1px dashed color-mix(in srgb, var(--primary) 52%, var(--line)); background: linear-gradient(135deg, rgba(255,255,255,.06), rgba(255,255,255,.01)); display: grid; place-items: center; color: var(--muted); }
      .fields { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; margin-top: 10px; }
      .field-box { min-height: 40px; border: 1px solid var(--line); border-radius: 8px; background: #08090b; padding: 7px; color: var(--muted); font-size: 12px; }
      .bottom-nav { display: grid; grid-template-columns: repeat(${Math.min(navItems.length, 5)}, 1fr); gap: 4px; padding: 8px; border-top: 1px solid var(--line); background: #090b0e; }
      .bottom-nav span { text-align: center; color: var(--muted); font-size: 11px; padding: 7px 2px; border-radius: 8px; }
      .bottom-nav span:first-child { color: #050507; background: var(--text); font-weight: 800; }
      .side-nav { display: grid; gap: 8px; margin: 18px 0; }
      .side-nav span { border: 1px solid var(--line); border-radius: 9px; padding: 10px 11px; color: var(--muted); }
      .side-nav span:first-child { color: var(--text); border-left-color: var(--warning); background: #17130a; }
      .note { border: 1px solid color-mix(in srgb, var(--warning) 45%, var(--line)); background: rgba(245,184,66,.08); border-radius: 12px; padding: 12px; color: #f6d58e; }
      @media (max-width: 980px) { .shell, .hero, .content { grid-template-columns: 1fr; } aside { border-right: 0; border-bottom: 1px solid var(--line); } .desktop-only { display: none; } main { padding: 16px; padding-bottom: 82px; } h1 { font-size: 26px; } .kpis { grid-template-columns: 1fr; } .mobile-fixed { display: grid; } }
      @media (min-width: 981px) { .mobile-fixed { display: none; } }
      .mobile-fixed { position: fixed; left: 12px; right: 12px; bottom: 12px; z-index: 20; border: 1px solid var(--line); border-radius: 16px; background: rgba(9,11,14,.92); backdrop-filter: blur(16px); padding: 6px; grid-template-columns: repeat(${Math.min(navItems.length, 5)}, 1fr); box-shadow: 0 18px 60px rgba(0,0,0,.4); }
      .mobile-fixed span { color: var(--muted); text-align: center; font-size: 11px; padding: 8px 2px; border-radius: 10px; }
      .mobile-fixed span:first-child { color: #050507; background: var(--text); font-weight: 800; }
    </style>
  </head>
  <body>
    <div class="shell">
      <aside class="desktop-only">
        <div class="brand">${logo ? `<img src="${logo}" alt="" />` : ''}<div><strong>${escapeHtml(project.name)}</strong><span>${escapeHtml(text(project.details.mode, 'Dark mode'))}</span></div></div>
        <nav class="side-nav">${navItems.map((item) => `<span>${escapeHtml(item)}</span>`).join('')}</nav>
        <div class="note"><strong>Wireframe intent</strong><p>This static preview mirrors the proposed navigation, document flow, and review screens so specs can be tuned before coding starts.</p></div>
        <div class="panel" style="margin-top: 14px"><h3>Build signals</h3><p>${escapeHtml(stackInterpretation(project.details))}</p><p>${escapeHtml(text(project.details.additionalTechStackRequirements, 'No additional stack requirements specified'))}</p><p>${escapeHtml(text(project.details.integrations, 'No integrations specified'))}</p></div>
      </aside>
      <main>
        <div class="topbar">
          <div class="brand">${logo ? `<img src="${logo}" alt="" />` : ''}<div><strong>${escapeHtml(project.name)}</strong><span>${escapeHtml(audience)}</span></div></div>
          <div class="actions">
            <span class="button">${escapeHtml(spec.secondaryAction)}</span>
            <span class="button primary">${escapeHtml(spec.primaryAction)}</span>
          </div>
        </div>
        <section class="hero">
          <div class="panel hero-card">
            <div>
              <small>${escapeHtml(runtime)} + ${escapeHtml(backend)}</small>
              <h1>${escapeHtml(spec.heroTitle)}</h1>
              <p>${escapeHtml(mission)}</p>
            </div>
            <div class="kpis">
              ${spec.kpis.map((kpi) => `<div class="kpi"><small>${escapeHtml(kpi.label)}</small><strong>${escapeHtml(kpi.value)}</strong></div>`).join('')}
            </div>
          </div>
          <div class="panel">
            <div class="section-head"><h2>${escapeHtml(spec.statusTitle)}</h2><span class="pill good">On track</span></div>
            <div class="timeline">
              ${workflow.map((item, index) => `<div class="timeline-row"><span class="dot"></span><div><strong>${index + 1}. ${escapeHtml(item.title)}</strong><p>${escapeHtml(item.detail)}</p></div></div>`).join('')}
            </div>
          </div>
        </section>
        <section class="content">
          <div class="panel">
            <div class="section-head"><h2>${escapeHtml(spec.checklistTitle)}</h2><span class="pill">${checklist.length} items</span></div>
            <div class="checklist">
              ${checklist.map((item, index) => `<div class="check-item"><span class="${index < 3 ? 'check' : 'check empty'}">${index < 3 ? '✓' : ''}</span><span>${escapeHtml(item)}</span><span class="${index < 3 ? 'pill good' : 'pill'}">${index < 3 ? 'Ready' : 'Missing'}</span></div>`).join('')}
            </div>
          </div>
          <div class="phone">
            <div class="phone-screen">
              <div class="phone-head"><strong>${escapeHtml(spec.mobileTitle)}</strong><span class="pill warn">${escapeHtml(spec.mobileBadge)}</span></div>
              <div class="phone-body">
                <div class="upload-card"><strong>${escapeHtml(spec.mobileCardTitle)}</strong><p>${escapeHtml(spec.mobileCardText)}</p><div class="capture">${escapeHtml(spec.mobilePreviewLabel)}</div><div class="fields">${spec.mobileFields.map((field) => `<div class="field-box">${escapeHtml(field)}</div>`).join('')}</div></div>
                <span class="button accent">${escapeHtml(spec.mobileAction)}</span>
              </div>
              <div class="bottom-nav">${navItems.slice(0, 5).map((item) => `<span>${escapeHtml(shortLabel(item))}</span>`).join('')}</div>
            </div>
          </div>
        </section>
        <section class="panel" style="margin-top: 16px">
          <div class="section-head"><h2>${escapeHtml(spec.tableTitle)}</h2><span class="pill">${escapeHtml(spec.tableNote)}</span></div>
          <table>
            <thead><tr>${spec.tableHeaders.map((heading) => `<th>${escapeHtml(heading)}</th>`).join('')}</tr></thead>
            <tbody>${statusRows.map((row) => `<tr>${row.map((cell) => `<td>${escapeHtml(cell)}</td>`).join('')}</tr>`).join('')}</tbody>
          </table>
        </section>
      </main>
    </div>
    <nav class="mobile-fixed">${navItems.slice(0, 5).map((item) => `<span>${escapeHtml(shortLabel(item))}</span>`).join('')}</nav>
  </body>
</html>`;
}

function deriveWireframeSpec(project: ArtifactProject): WireframeSpec {
  const appType = detectAppType(project);
  if (appType === 'invoice_factoring') return deriveInvoiceFactoringWireframeSpec(project);

  const entities = deriveEntities(project.details);
  const navItems = deriveNavItems(project.details, false);
  const workflow = summarizeWorkflow(project.details, false);
  return {
    appKind: 'generic_workflow',
    title: project.name,
    mission: project.description || text(project.details.mission, 'Mission pending'),
    audience: text(project.details.audience, 'Target audience to be refined'),
    runtime: text(project.details.runtimeOption, 'Runtime TBD'),
    backend: text(project.details.backendFramework, 'Backend TBD'),
    themeMode: text(project.details.mode, 'Dark mode'),
    fontFamily: text(project.details.primaryFont, 'Inter'),
    logoHref: '',
    primary: '',
    accent: '',
    success: '',
    navItems,
    entities,
    workflow,
    checklist: entities.slice(0, 6),
    statusRows: [
      ['REC-1042', entities[0] ?? 'Primary record', 'Open', 'Submitted'],
      ['REC-1038', entities[1] ?? 'Supporting item', 'Draft', 'Needs review'],
      ['REC-1031', entities[2] ?? 'Completed item', 'Done', 'Archived']
    ],
    kpis: [
      { label: 'Ready items', value: '8' },
      { label: 'Open records', value: '24' },
      { label: 'Completed', value: '71%' }
    ],
    heroTitle: project.name,
    primaryAction: `Start ${text(project.details.requirementName, 'workflow').toLowerCase()}`,
    secondaryAction: 'Add record',
    statusTitle: 'Workflow status',
    checklistTitle: 'Primary checklist',
    tableTitle: 'Recent records',
    tableNote: 'Live preview',
    tableHeaders: ['ID', 'Record', 'State', 'Status'],
    mobileTitle: 'Capture item',
    mobileBadge: 'Review',
    mobileCardTitle: entities[0] ?? 'Record details',
    mobileCardText: 'Review the important fields before saving.',
    mobilePreviewLabel: 'Preview area',
    mobileFields: ['Name', 'Date', 'Owner', 'Status'],
    mobileAction: 'Save item',
    stackNote: stackInterpretation(project.details),
    integrationNote: text(project.details.integrations, 'No integrations specified')
  };
}

function deriveInvoiceFactoringWireframeSpec(project: ArtifactProject): WireframeSpec {
  return {
    appKind: 'invoice_factoring',
    title: project.name,
    mission: project.description || text(project.details.mission, 'Mission pending'),
    audience: text(project.details.audience, 'Target audience to be refined'),
    runtime: text(project.details.runtimeOption, 'Runtime TBD'),
    backend: text(project.details.backendFramework, 'Backend TBD'),
    themeMode: text(project.details.mode, 'Dark mode'),
    fontFamily: text(project.details.primaryFont, 'Inter'),
    logoHref: '',
    primary: '',
    accent: '',
    success: '',
    navItems: deriveNavItems(project.details, true),
    entities: ['Users', 'Company details', 'Documents', 'Invoices', 'Factoring companies', 'Applications'],
    workflow: [
      { title: 'Onboard company', detail: 'Collect company identity, contact details, and secure profile basics.' },
      { title: 'Complete documents', detail: 'Upload, photograph, OCR, review, and save required application files.' },
      { title: 'Attach invoices', detail: 'Add invoices, validate readiness, then submit factoring packages.' },
      { title: 'Track funding', detail: 'Monitor submitted, follow up, approved, funded, and rejected states.' }
    ],
    checklist: ['Company profile', 'EIN letter', 'Bank statement', 'Tax return', 'Driver license', 'Invoice PDF'],
    statusRows: [
      ['INV-1042', 'Riverbend Materials', '$18,420', 'Submitted'],
      ['INV-1038', 'Northline Freight', '$7,950', 'OCR needed'],
      ['INV-1031', 'Apex Supply', '$12,300', 'Funded']
    ],
    kpis: [
      { label: 'Ready docs', value: '4/6' },
      { label: 'Open invoices', value: '12' },
      { label: 'Funded 30 days', value: '$42.6k' }
    ],
    heroTitle: 'Prepare, submit, and track invoice factoring packages.',
    primaryAction: 'Start factoring wizard',
    secondaryAction: 'Add invoice',
    statusTitle: 'Application status',
    checklistTitle: 'Factoring checklist',
    tableTitle: 'Invoices and funding',
    tableNote: 'Factor enabled when docs are complete',
    tableHeaders: ['ID', 'Customer', 'Amount', 'Status'],
    mobileTitle: 'Upload document',
    mobileBadge: 'OCR review',
    mobileCardTitle: 'Bank statement',
    mobileCardText: 'Capture or upload, confirm extracted fields, then save securely.',
    mobilePreviewLabel: 'Camera / file preview',
    mobileFields: ['Name', 'Date', 'Amount', 'Status'],
    mobileAction: 'Save and next document',
    stackNote: stackInterpretation(project.details),
    integrationNote: text(project.details.integrations, 'No integrations specified')
  };
}

function detectAppType(project: ArtifactProject) {
  const source = `${project.name} ${project.description} ${text(project.details.mainWorkflow, '')} ${text(project.details.dataNeeds, '')}`;
  if (/\bfactoring\b|\binvoice factoring\b/i.test(source)) return 'invoice_factoring';
  return 'general_workflow';
}

function deriveNavItems(details: Record<string, unknown>, isRiteFact: boolean) {
  const source = `${text(details.mainWorkflow, '')} ${text(details.mission, '')}`;
  const preferred = isRiteFact ? ['Home', 'Apply', 'Documents', 'Invoices', 'Status', 'Settings'] : ['Home', 'Workflow', 'Records', 'Status', 'Settings'];
  if (isRiteFact) return preferred;
  const found = preferred.filter((item) => new RegExp(`\\b${escapeRegExp(item)}\\b`, 'i').test(source));
  return found.length >= 4 ? found : preferred;
}

function deriveEntities(details: Record<string, unknown>) {
  const raw = text(details.dataNeeds, '');
  const entities = raw
    .split(/[,;\n]+/)
    .map((item) => item.replace(/\([^)]*\)/g, '').trim())
    .filter((item) => item.length > 2)
    .slice(0, 8);
  return entities.length ? entities : ['Users', 'Records', 'Files', 'Statuses', 'Settings'];
}

function summarizeWorkflow(details: Record<string, unknown>, isRiteFact: boolean) {
  if (isRiteFact) {
    return [
      { title: 'Onboard company', detail: 'Collect company identity, contact details, and secure profile basics.' },
      { title: 'Complete documents', detail: 'Upload, photograph, OCR, review, and save required application files.' },
      { title: 'Attach invoices', detail: 'Add invoices, validate readiness, then submit factoring packages.' },
      { title: 'Track funding', detail: 'Monitor submitted, follow up, approved, funded, and rejected states.' }
    ];
  }
  const sentences = text(details.mainWorkflow, text(details.userActions, 'User completes the primary workflow and reviews the result.'))
    .split(/\n+|(?<=\.)\s+/)
    .map((line) => line.replace(/^\d+\.\s*/, '').trim())
    .filter(Boolean)
    .slice(0, 4);
  return (sentences.length ? sentences : ['Open the app', 'Complete the main task', 'Review status', 'Save the result']).map((line, index) => ({
    title: ['Start', 'Capture', 'Review', 'Finish'][index] ?? `Step ${index + 1}`,
    detail: line
  }));
}

function shortLabel(value: string) {
  return value.replace('App Builder', 'Build').replace('Settings', 'More');
}

function normalizeHex(value: string | undefined, fallback: string) {
  if (!value) return fallback;
  const trimmed = value.trim();
  if (/^#[0-9a-fA-F]{6}$/.test(trimmed)) return trimmed.toLowerCase();
  if (/^[0-9a-fA-F]{6}$/.test(trimmed)) return `#${trimmed.toLowerCase()}`;
  return fallback;
}

function escapeCssIdentifier(value: string) {
  return value.replace(/[^a-zA-Z0-9 _-]/g, '').split(',')[0] || 'Inter';
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function logoExtension(fileName: string, mimeType: string) {
  const fromName = fileName.toLowerCase().match(/\.([a-z0-9]+)$/)?.[1];
  if (fromName && ['png', 'jpg', 'jpeg', 'webp', 'svg'].includes(fromName)) return fromName === 'jpg' ? 'jpeg' : fromName;
  if (mimeType.includes('svg')) return 'svg';
  if (mimeType.includes('webp')) return 'webp';
  if (mimeType.includes('jpeg') || mimeType.includes('jpg')) return 'jpeg';
  return 'png';
}

function text(value: unknown, fallback: string) {
  return typeof value === 'string' && value.trim() ? value.trim() : fallback;
}

function isInvoiceFactoringProject(project: ArtifactProject) {
  const source = `${project.name} ${project.description} ${text(project.details.mission, '')} ${text(
    project.details.mainWorkflow,
    ''
  )} ${text(project.details.dataNeeds, '')}`;
  return /\bfactoring\b|\binvoice factoring\b/i.test(source);
}

function normalizeDomainText(value: string, isFactoringProject: boolean) {
  if (!isFactoringProject) return value;
  return value
    .replace(/Desktop layout is right sidebar/gi, 'Desktop layout uses a left sidebar')
    .replaceAll('App Builder', 'Apply')
    .replace(/\bDocs\b/g, 'Documents')
    .replace(/\bRecords\b/g, 'Documents')
    .replace(/Home,\s*Apply,\s*Documents,\s*Invoices,\s*Status/gi, 'Home, Apply, Documents, Invoices, Status')
    .replace(/Home,\s*Apply,\s*Records,\s*Invoices,\s*Status/gi, 'Home, Apply, Documents, Invoices, Status');
}

function list(value: unknown) {
  return Array.isArray(value) ? value.map(String).filter(Boolean).join(', ') || 'None selected' : 'None selected';
}

function safeSegment(value: string, fallback: string) {
  const normalized = value.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
  return normalized || fallback.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'project';
}

function yamlBlock(lines: string[]) {
  return `\n${lines.flatMap((line) => line.split('\n')).map((line) => `  ${line}`).join('\n')}`;
}

function stackInterpretation(details: Record<string, unknown>) {
  const stack = text(details.technologyStack, '');
  const backend = text(details.backendFramework, '');
  if (/sqlite/i.test(stack) && /supabase/i.test(backend)) {
    return 'Use Supabase as the production backend. Treat SQLite in the selected stack as local development, cache, test fixture, or lightweight prototype storage only when it does not conflict with Supabase.';
  }
  return 'Use the selected technology stack and backend together; if they conflict, prefer the explicit backend framework selection.';
}

function escapeHtml(value: string) {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#039;');
}
